Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
displayBytes(bytes=[[X]],td_font_size="2.5em", th_font_size="1.5em")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[11], line 1[0m
[0;32m----> 1[0m [43mdisplayBytes[49m[43m([49m[38;5;28;43mbytes[39;49m[38;5;241;43m=[39;49m[43m[[49m[43m[[49m[43mX[49m[43m][49m[43m][49m[43m,[49m[43mtd_font_size[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m2.5em[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mth_font_size[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m1.5em[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/ope-docubook/content/python/common.py:368[0m, in [0;36mdisplayBytes[0;34m(bytes, labels, labelstitle, prefixvalues, prefixcolumns, numbits, dtype, columns, center, th_font_size, th_border_color, th_hover_border_color, td_font_size, td_height, border_color, tr_hover_bgcolor, tr_hover_border_color, td_hover_bgcolor, td_hover_color, disp, prehtml, posthtml)[0m
[1;32m    366[0m [38;5;66;03m# if no row labels hide them[39;00m
[1;32m    367[0m [38;5;28;01mif[39;00m ([38;5;28mlen[39m(labels)[38;5;241m==[39m[38;5;241m0[39m):
[0;32m--> 368[0m     [43mbody[49m[38;5;241;43m.[39;49m[43mhide_index[49m()
[1;32m    369[0m [38;5;66;03m# if no column labels hide them [39;00m
[1;32m    370[0m [38;5;28;01mif[39;00m ([38;5;28mlen[39m(columns)[38;5;241m==[39m[38;5;241m0[39m):

[0;31mAttributeError[0m: 'Styler' object has no attribute 'hide_index'
AttributeError: 'Styler' object has no attribute 'hide_index'

